unstable_features = true
max_width = 200
array_width = 60
trailing_comma = "Never"
match_block_trailing_comma = true
where_single_line = true
use_small_heuristics = "Max"
chain_width = 60
force_multiline_blocks = true
hex_literal_case = "Upper"
ignore = [
    "src/types.rs",
    "src/foo/bar.rs",
]